import { useQuery } from '@tanstack/react-query'
import { BookOpen, CalendarDays, Flame, GraduationCap, IndianRupee, ShieldCheck, Sparkles, Target, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge, Button, Card, StatCard } from '../../components/ui'
import { api } from '../../lib/api'
import { useAuthStore } from '../../stores/auth.store'

export function StudentDashboardPage(){const user=useAuthStore(s=>s.user)!;const {data,isLoading,isError}=useQuery({queryKey:['student-dashboard'],queryFn:()=>api.get('/students/dashboard').then(r=>r.data.data)});return <><PageHeader title={`Good day, ${user.name.split(' ')[0]}!`} subtitle="Ready to continue your learning journey?" action={<Link to="/student/practice"><Button><Sparkles size={18}/>Start AI Practice</Button></Link>}/>{isLoading?<LoadingCards/>:isError?<ErrorCard/>:<><div className="stat-grid"><StatCard label="Current level" value={data.profile.level} icon={<GraduationCap/>}/><StatCard label="Total XP" value={data.profile.xp} icon={<Target/>}/><StatCard label="Day streak" value={`${data.profile.streak} days`} icon={<Flame/>}/><StatCard label="Accuracy" value={`${Math.round(data.profile.accuracyPercent)}%`} icon={<BookOpen/>}/></div><div className="content-grid"><Card><h3>XP progress</h3><div className="progress"><span style={{width:`${data.xpProgressPercent}%`}}/></div><p className="muted">Keep practising to reach the next level.</p></Card><Card className="ai-card"><Badge tone="purple">AI recommendation</Badge><h3>{data.recommendations[0]}</h3><p className="muted">Personalised suggestions will improve as you complete sessions.</p><Link to="/student/practice">Start now →</Link></Card></div><div className="content-grid"><Card><h3>Weak topics</h3><EmptyText text="No weak topics detected yet."/></Card><Card><h3>Upcoming sessions</h3><EmptyText text="You have no upcoming teacher sessions."/></Card></div></>}</>}

export function TeacherDashboardPage(){
  const user=useAuthStore(s=>s.user)!
  const {data,isLoading,isError}=useQuery({queryKey:['teacher-dashboard'],queryFn:()=>api.get('/teachers/dashboard').then(r=>r.data.data)})
  const status=data?.applicationStatus as 'draft'|'pending'|'approved'|'rejected'|undefined
  const statusTitle=status==='rejected'?'Your profile needs changes':status==='pending'?'Your application is under review':'Complete your teacher profile'
  const statusMessage=status==='rejected'?(data?.profile?.rejectionReason||'Review the admin feedback and resubmit your profile.'):status==='pending'?'Your documents and professional details are waiting for admin verification.':'Add your teaching details, standards, subjects, and qualification documents before submitting.'
  return <>
    <PageHeader title={`Welcome, ${user.name}`} subtitle="Manage your teaching schedule and student requests." action={<Link to="/teacher/slots"><Button><CalendarDays size={18}/>Manage Slots</Button></Link>}/>
    {isLoading?<LoadingCards/>:isError?<ErrorCard/>:<>
      <div className="stat-grid"><StatCard label="Today's sessions" value={data.todaySessions.length} icon={<CalendarDays/>}/><StatCard label="Pending requests" value={data.pendingRequests} icon={<BookOpen/>}/><StatCard label="Rating" value={data.profile.rating.toFixed(1)} icon={<Sparkles/>}/><StatCard label="Total earnings" value={`₹${data.profile.totalEarnings}`} icon={<IndianRupee/>}/></div>
      {!data.profile.isApproved&&<Card className="warning-card"><Badge tone={status==='rejected'?'danger':status==='pending'?'warning':'neutral'}>{status||'draft'}</Badge><h3>{statusTitle}</h3><p className="muted">{statusMessage}</p><Link to="/teacher/profile">{status==='rejected'?'Update and resubmit':'Complete profile'} →</Link></Card>}
      <Card><h3>Upcoming sessions</h3><EmptyText text="No sessions scheduled."/></Card>
    </>}
  </>
}

export function AdminDashboardPage(){const {data,isLoading,isError}=useQuery({queryKey:['admin-dashboard'],queryFn:()=>api.get('/admin/dashboard').then(r=>r.data.data)});return <><PageHeader title="Admin Dashboard" subtitle="Platform overview and important actions." action={<Link to="/admin/teachers"><Button><ShieldCheck size={18}/>Review Teachers</Button></Link>}/>{isLoading?<LoadingCards/>:isError?<ErrorCard/>:<div className="stat-grid"><StatCard label="Students" value={data.students} icon={<GraduationCap/>}/><StatCard label="Teachers" value={data.teachers} icon={<UsersRound/>}/><StatCard label="Pending approvals" value={data.pendingTeachers} icon={<ShieldCheck/>}/><StatCard label="Active subjects" value={data.subjects} icon={<BookOpen/>}/></div>}<div className="content-grid"><Card><h3>Revenue overview</h3><div className="chart-placeholder">Analytics chart will be connected with the fees module.</div></Card><Card><h3>System alerts</h3><EmptyText text="No critical alerts."/></Card></div></>}

export function TeacherApprovalsPage(){const {data=[],refetch}=useQuery({queryKey:['pending-teachers'],queryFn:()=>api.get('/admin/teachers/pending').then(r=>r.data.data)});const decide=async(id:string,decision:'approved'|'rejected')=>{await api.patch(`/admin/teachers/${id}/decision`,{decision,reason:decision==='rejected'?'Profile requires changes':undefined});await refetch()};return <><PageHeader title="Teacher Approvals" subtitle="Review profiles before teachers appear publicly."/>{data.length===0?<Card><EmptyText text="No pending teacher applications."/></Card>:<div className="list-grid">{data.map((p:any)=><Card key={p._id}><div className="row-between"><div><h3>{p.userId?.name}</h3><p className="muted">{p.userId?.email}</p></div><Badge tone="warning">Pending</Badge></div><p>{p.qualification||'Qualification not added'}</p><p className="muted">{p.experienceYears} years experience · ₹{p.hourlyRate}/hour</p><div className="button-row"><Button onClick={()=>decide(p._id,'approved')}>Approve</Button><Button className="button-secondary" onClick={()=>decide(p._id,'rejected')}>Request changes</Button></div></Card>)}</div>}</>}

export function SubjectsPage(){const {data=[],isLoading}=useQuery({queryKey:['subjects'],queryFn:()=>api.get('/subjects').then(r=>r.data.data)});return <><PageHeader title="Subjects & Topics" subtitle="Curriculum configuration foundation."/>{isLoading?<LoadingCards/>:<div className="list-grid">{data.map((s:any)=><Card key={s._id}><div className="row-between"><h3>{s.name}</h3><Badge tone={s.isAiEnabled?'purple':'neutral'}>{s.isAiEnabled?'AI enabled':'AI disabled'}</Badge></div><p className="muted">{s.description}</p><p>{s.topics.length} topics</p></Card>)}</div>}</>}

export function ComingSoonPage({title}:{title:string}){return <><PageHeader title={title} subtitle="The route and layout are ready for this module."/><Card className="coming-soon"><Sparkles size={34}/><h3>Next module</h3><p className="muted">This page will be implemented against the approved UI and database model.</p></Card></>}
export function ProfilePage(){return <><PageHeader title="My Profile" subtitle="Personal and role-specific profile settings."/><Card><p className="muted">Profile API is ready at <code>/users/me</code>. The detailed edit form and media upload are the next frontend task.</p></Card></>}
function PageHeader({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <div className="page-header"><div><h1>{title}</h1><p className="muted">{subtitle}</p></div>{action}</div>}
function EmptyText({text}:{text:string}){return <div className="empty-box">{text}</div>}
function LoadingCards(){return <div className="stat-grid">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div>}
function ErrorCard(){return <Card><div className="alert error">Could not load this dashboard. Check that the API and MongoDB are running.</div></Card>}
